### ISSUE TITLE
can i have a clear image of arduino breadboard

### ISSUE THREAD

**Issue by amberng97** [tomlehto/Bluetooth-LED-Dice#1]
can i have a clear image of your arduino breadboard setup?we need it as a reference for our school final exam project,pls reply asap and thankyou

**Comment by tomlehto** [comment]
Unfortunately no because I don't have it set up anymore. It was just Arduino Uno digital outputs 7-13 connected to positive leg of each LED through a resistor (maybe ~200ohm?). Then connect every LEDs negative leg to ground. Then, you can modify the diceArray binary values so that they work correct for you (first bitstring of the array represents dice value 1, second represents 2 etc.).

**Comment by amberng97** [comment]
thanks for the reply,i will try it myself~

Tomi Lehto <notifications@github.com> 于 2019年1月10日周四 01:25写道：
